# Generated by Django 5.1.5 on 2025-01-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='cliente',
        ),
    ]
