# Generated by Django 5.1.5 on 2025-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_nota_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_fin_membresia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
