# Generated by Django 5.1.5 on 2025-01-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_fecha_fin_membresia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_fin_membresia',
        ),
    ]
