# Generated by Django 5.1.5 on 2025-01-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_cliente_fecha_fin_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
